### ISSUE TITLE
Update to pom-scijava-base 3.2.0

### ISSUE THREAD

**Issue by ctrueden** [imglib/pom-imglib2#1]
This POM needs to be updated to extend `pom-scijava-base` version `3.2.0` or later:

* Version `3.1.3` contains critical fixes to the build system which prevented successful deployment of release versions in many scenarios—in particular, there was attempted double-deployment of the `-sources` JAR. Without this update, it will not be feasible to release imglib2 components via the new Travis-based release scheme.
* Version `3.2.0` (not yet released as of this writing) contains a new feature (scijava/pom-scijava-base@54bf6664462db3cb538a39986005ac91bded13d5) enabling enforcement of a minimum Java version. And the `imglib2` core library would like to make use of this (imglib/imglib2@156d365aa3b5aa2a7df897532469bc99fd9f037d).

**Comment by hanslovsky** [comment]
Fixed in 1aafe9d2ccdf7d73b7fd02922e71d50666fe2d25 with an update of the parent `pom-scijava` version to `19.0.0`, which in turn has `pom-scijava-base-3.2.0` as parent.
