### ISSUE TITLE
Update to imglib2 4.x

### ISSUE THREAD

**Issue by ctrueden** [imglib/pom-imglib2#2]
This POM declares several now-outdated versions of imglib2 components. In particular, it declares imglib2 3.x. It needs to be updated to manage imglib2 core at 4.x, to avoid version skew between imglib2 components and everything else in the SciJava component collection.

**Comment by imagejan** [comment]
This was done in https://github.com/imglib/pom-imglib2/commit/1aafe9d2ccdf7d73b7fd02922e71d50666fe2d25 and can be closed.

**Comment by tpietzsch** [comment]
👍
